# ansible N1 -m file -a "path/home/ec2-user/ all_dir state=directory"
---
- name: Install HTTP servers
  hosts: N2
  become: yes
  tasks:
    - name: Install HTTPD
      dnf:
        name: HTTPD
        state: present

    - name: start HTTPD
      service:
        name: httpd
        state: started


    - name: enable and start HTTPD
      service:
        name: httpd
        enabled: yes
        state: started
...