---
- name: Deploy Maintenance Page on server
  hosts: N2
  become: yes

  tasks:
    - name: update maintenance page
      copy:
        src: file/maintenance.html
        dest: /var/www/html/index.html